# Generated by Django 4.1.7 on 2023-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_monan'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='image',
            field=models.ImageField(null=True, upload_to='monan/%Y/%m'),
        ),
    ]
