# Generated by Django 4.1.7 on 2023-03-30 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_tag_dichvu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanhCuoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('minimum_price', models.IntegerField()),
                ('number_of_tables', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='sanhcuoi/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='tags',
            field=models.ManyToManyField(related_name='dichvus', to='wedding.tag'),
        ),
    ]
