# Generated by Django 4.1.7 on 2023-03-31 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_sanhcuoi_alter_dichvu_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monan',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
