# Generated by Django 4.1.7 on 2023-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_monan_active_monan_created_date_monan_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(null=True, upload_to='nguoidung/%Y/%m'),
        ),
    ]
