# Generated by Django 4.1.7 on 2023-04-02 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_binhluan'),
    ]

    operations = [
        migrations.CreateModel(
            name='XepHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('rate', models.SmallIntegerField(default=0)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanhcuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.sanhcuoi')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sanhcuoi', 'nguoidung')},
            },
        ),
        migrations.CreateModel(
            name='Thich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('liked', models.BooleanField(default=True)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanhcuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.sanhcuoi')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sanhcuoi', 'nguoidung')},
            },
        ),
    ]
